### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by StasWideweb** [jrrdnx/craft-search-assistant#1]
There was a problem with the keywords. Due to the fact that we are expanding the initial search like this:
```
{% set queryParamsText = searchQueryLine
                ~ ' OR "'~ searchQueryLine ~ '"'
                ~ ' OR *'~ searchQueryLine
                ~ ' OR ' ~ searchQueryLine~'*'
                ~ ' OR *'~searchQueryLine~'*'
                %}
```
Keywords do not record what the user entered into the search bar, but our advanced query:
`test OR "test" OR *test OR test* OR *test*`
Could you give advice on how to get around this point so that the keywords capture exactly the query that the user enters?

**Comment by jrrdnx** [comment]
Thanks for opening this issue, I've added this use case to my list of tests.

This is fixed in [1.1.2](https://github.com/jrrdnx/craft-search-assistant/releases/tag/1.1.2)
