### ISSUE TITLE
Only logging last word in querys

### ISSUE THREAD

**Issue by chrisrowe** [jrrdnx/craft-search-assistant#2]
If I search "foo bar" only "bar" appears as the searched keyword, "foo" isn't present

**Comment by jrrdnx** [comment]
Thanks for reporting! This is fixed in [1.1.3](https://github.com/jrrdnx/craft-search-assistant/releases/tag/1.1.3)

**Comment by chrisrowe** [comment]
Thanks, but I'm not seeing anything appearing in the CP any more

**Comment by chrisrowe** [comment]
Sorry you're right, I guess I was logged in. It's working now https://up.chri.sr/Screen-Shot-2024-02-23-12-11-42.17-1708690305.png
